package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.ItemDo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ItemDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Tue Jan 15 11:03:18 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Tue Jan 15 11:03:18 CST 2019
     */
    int insert(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Tue Jan 15 11:03:18 CST 2019
     */
    int insertSelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Tue Jan 15 11:03:18 CST 2019
     */
    ItemDo selectByPrimaryKey(Integer id);

    List<ItemDo> selectItemList();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Tue Jan 15 11:03:18 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Tue Jan 15 11:03:18 CST 2019
     */
    int updateByPrimaryKey(ItemDo record);

    /**
     * 销量增加
     * @param id
     * @param amount
     * @return
     */
    int increaseSales(@Param("id")Integer id, @Param("amount")Integer amount);

}