package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.SequenceInfoDo;
import org.springframework.stereotype.Repository;

@Repository
public interface SequenceInfoDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jan 16 10:24:37 CST 2019
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jan 16 10:24:37 CST 2019
     */
    int insert(SequenceInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jan 16 10:24:37 CST 2019
     */
    int insertSelective(SequenceInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jan 16 10:24:37 CST 2019
     */
    SequenceInfoDo selectByPrimaryKey(String name);

    SequenceInfoDo getSequenceByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jan 16 10:24:37 CST 2019
     */
    int updateByPrimaryKeySelective(SequenceInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jan 16 10:24:37 CST 2019
     */
    int updateByPrimaryKey(SequenceInfoDo record);
}